# Generated by Django 5.2.11 on 2026-02-26 11:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Стандартный телефон'),
        ),
    ]
