# Generated by Django 5.2.11 on 2026-02-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_phone_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
