# Generated by Django 5.2.11 on 2026-02-26 13:47

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():

        if not flat.owners_phonenumber:
            continue

        try:
            parsed = phonenumbers.parse(flat.owners_phonenumber, 'RU')

            if phonenumbers.is_valid_number(parsed):
                flat.owner_pure_phone = phonenumbers.format_number(
                    parsed,
                    phonenumbers.PhoneNumberFormat.E164
                )
            else:
                flat.owner_pure_phone = None

            flat.save(update_fields=['owner_pure_phone'])

        except phonenumbers.NumberParseException:
            flat.owner_pure_phone = None
            flat.save(update_fields=['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
    ]
