# Generated by Django 5.2.11 on 2026-02-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_remove_flat_owners_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_phone',
        ),
    ]
