# Generated by Django 5.2.11 on 2026-02-27 11:55

from django.db import migrations

def fill_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():

        if not flat.owner:
            continue

        Owner.objects.get_or_create(
            name=flat.owner.strip(),
            phone=flat.owner_pure_phone,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owner_model),
    ]
