# Generated by Django 5.2.11 on 2026-02-27 12:01

from django.db import migrations

def link_owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():

        if not flat.owner:
            continue

        owner = Owner.objects.filter(
            name=flat.owner.strip(),
            phone=flat.owner_pure_phone
        ).first()

        if owner:
            owner.flats.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20260227_2055'),
    ]

    operations = [
        migrations.RunPython(link_owners_and_flats),
    ]
