# Generated by Django 5.2.11 on 2026-02-28 08:42

from django.db import migrations

def clean_invalid_complaints(apps, schema_editor):
    Complaint = apps.get_model('property', 'Complaint')

    Complaint.objects.filter(author__isnull=True).delete()
    Complaint.objects.filter(flat__isnull=True).delete()
    Complaint.objects.filter(text__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_complaint_author_alter_complaint_flat_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_invalid_complaints),
    ]
